version: "3"
services:
  book-catalog:
    image: book-catalog
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
      - "8082:8082"
    environment:
      - DATABASE_URL=postgresql://booksdb_sv6s_user:ku6R3ciKcn1hM5RLPJQ1wCEhtiOLUtAR@dpg-crd5i4t2ng1s73fok0g0-a.oregon-postgres.render.com/booksdb_sv6s

  inventory-management:
    image: inventory-management
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgresql://booksdb_sv6s_user:ku6R3ciKcn1hM5RLPJQ1wCEhtiOLUtAR@dpg-crd5i4t2ng1s73fok0g0-a.oregon-postgres.render.com/booksdb_sv6s
